apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: mongodb
  finalizers:
    - percona.com/delete-psmdb-pods-in-order
spec:
  crVersion: 1.22.0
  pause: false
  unmanaged: false
  enableVolumeExpansion: false

  image: {{ .Values.image | quote }}
  imagePullPolicy: {{ .Values.imagePullPolicy | quote }}

  {{- if .Values.users }}
  users:
    {{- range .Values.users }}
    - name: {{ .name }}
      {{- if .db }}
      db: {{ .db }}
      {{- end }}
      passwordSecretRef:
        name: mongodb-users
        key: {{ .name }}_pass
      {{- if .roles }}
      roles:
        {{- range .roles }}
        - name: {{ .name }}
          db: {{ .db }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}

  unsafeFlags:
    backupIfUnhealthy: false
    mongosSize: false
    terminationGracePeriod: false
    tls: false
    # allow single node cluster: disable in prod
    replsetSize: true

  multiCluster:
    enabled: false
  secrets:
    users: psmdb-db-secrets-auto
  updateStrategy: SmartUpdate

  replsets:
  - name: rs0
    size: 1
    affinity:
      antiAffinityTopologyKey: none
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        memory: 512Mi
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: {{ .Values.storage.size | quote }}
        storageClassName: {{ .Values.storage.class | quote }}
    expose:
      enabled: false
    hidden:
      enabled: false
      size: 2
    nonvoting:
      enabled: false
      size: 3
    arbiter:
      enabled: false
      size: 1

  upgradeOptions:
    apply: Never
  pmm:
    enabled: false
    image: "percona/pmm-client:3.6.0"
  sharding:
    enabled: false
  backup:
    enabled: false
    image: "percona/percona-backup-mongodb:2.12.0"
  logcollector:
    enabled: false
