{{- if .Values.users }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-users
data:
  {{- range .Values.users }}
  {{ .name }}_pass: {{ .name | b64enc | quote }}
  {{- end }}
{{- end }}
