{{- range $.Values.users }}
{{ $user := .name -}}
{{- range .db }}
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ $user }}-{{ . }}
spec:
  name: {{ . }}
  owner: {{ $user }}
  cluster:
    name: postgres
---
{{- end -}}
{{- end -}}
