{{- range $.Values.autoCreateDB }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: "{{ . }}-cnpg-user"
  labels:
    cnpg.io/reload: "true"
data:
  username: {{ . | b64enc | quote }}
  password: {{ . | b64enc | quote }}
---
{{- end -}}
