{{- if .Values.autoCreateDB }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-clickhouse-db-create-script"
data:
  script.sh: |-
    ch_isready() {
      while true; do
        clickhouse-client \
          --host clickhouse-{{ .Release.Name }}-clickhouse \
          -q ""
        exit_code="$?"

        if [[ "$exit_code" = "0" ]]; then
          break
        else
          echo "Waiting for clickhouse"
          sleep 2
          continue
        fi
      done
    }

    echo "Waiting for ClickHouse to be ready..."
    ch_isready
    echo "ClickHouse is ready"

    echo "Creating databases..."
    clickhouse-client \
      --host clickhouse-{{ .Release.Name }}-clickhouse <<- EOF
    {{- range $.Values.autoCreateDB }}
      CREATE USER IF NOT EXISTS {{ . }} IDENTIFIED
      WITH sha256_password
      BY '{{ . }}' DEFAULT DATABASE {{ . }};
      CREATE DATABASE IF NOT EXISTS {{ . }};
      GRANT ALL ON {{ . }}.* TO {{ . }};
    {{- end }}
    EOF
    echo "Database initialization complete"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-clickhouse-db-create-{{ join "-" $.Values.autoCreateDB | sha256sum  | trunc 8 }}"
spec:
  ttlSecondsAfterFinished: 86400 # 1Day
  template:
    spec:
      volumes:
        - name: "{{ .Release.Name }}-clickhouse-db-create-script"
          configMap:
            name: "{{ .Release.Name }}-clickhouse-db-create-script"
      containers:
      - name: clickhouse-db-create
        image: "{{ .Values.image }}"
        volumeMounts:
          - mountPath: "/var/script.sh"
            name: "{{ .Release.Name }}-clickhouse-db-create-script"
            subPath: script.sh
            readOnly: true
        command: ["/bin/bash", "/var/script.sh"]
      restartPolicy: Never
{{- end }}
