storage:
  size: "8Gi"
  ClassName: "openebs-lvm"

users:
  dapr:
    authentication:
      type: tls
    authorization:
      type: simple
      acls:
        - resource:
            type: topic
            name: dapr
            patternType: literal
          host: "*"
          operations:
            - Create
            - Write
            - Read
            - Delete
            - Describe
            - Alter
            - DescribeConfigs
            - AlterConfigs
            - ClusterAction
            - IdempotentWrite

strimzi-kafka-operator:
  enabled: true
