monitoring:
  redis:
    endpoint: "valkey.valkey:6379"
    password: "valkey"
  postgres:
    endpoint: "postgres-r.postgres:5432"
    username: "monitoring"
    password: "monitoring"
  clickhouse:
    endpoint: "clickhouse-altinity-clickhouse-operator-metrics.clickhouse:8888"
    path: "/metrics"

opentelemetry-operator:
  enabled: true
