signoz:
  enabled: true
  clickhouse:
    enabled: false

  externalClickhouse:
    host: clickhouse-clickhouse-clickhouse.clickhouse
    user: signoz
    password: signoz
    database: signoz_metrics
    traceDatabase: signoz_traces
    logDatabase: signoz_logs
    meterDatabase: signoz_meter

  signoz:
    env:
      #  TODO: setup email
      # signoz_emailing_enabled: todo
      # signoz_emailing_smtp_address: todo
      # signoz_emailing_smtp_from: todo
      # signoz_emailing_smtp_auth_username: todo
      # signoz_emailing_smtp_auth_password: todo
      signoz_sqlstore_provider: postgres
      signoz_sqlstore_postgres_dsn: postgres://signoz:signoz@postgres-rw.postgres:5432/signoz?sslmode=disable
    persistence:
      enabled: false
