apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-clickhouse-db-create-script"
data:
  script.sh: |-
    ch_isready() {
      while true; do
        clickhouse-client \
          --host clickhouse-{{ .Release.Name }}-clickhouse \
          -q ""
        exit_code="$?"

        if [[ "$exit_code" = "0" ]]; then
          break
        else
          echo "Waiting for clickhouse"
          sleep 2
          continue
        fi
      done
    }

    echo "Waiting for ClickHouse to be ready..."
    ch_isready
    echo "ClickHouse is ready"

    echo "Creating databases..."
    clickhouse-client \
      --host clickhouse-{{ .Release.Name }}-clickhouse <<- EOF
    {{- range $.Values.users }}
      {{ $name := .name -}}

      CREATE USER IF NOT EXISTS {{ .name }} IDENTIFIED
      WITH sha256_password BY '{{ .name }}';

      {{ range .grants -}}
      grant {{ . }} TO '{{ $name }}';
      {{ end }}

      {{ range .databases -}}
      CREATE DATABASE IF NOT EXISTS {{ . }};
      grant ALL ON {{ . }}.* TO {{ $name }};
      {{ end -}}

      {{ if .databases -}}
      ALTER USER '{{ .name }}' DEFAULT DATABASE '{{ first .databases }}';
      {{- end }}
    {{- end }}
    EOF
