image: altinity/clickhouse-server:25.3.8.10042.altinitystable
storageClass: local-path
size: 8Gi
reclaimPolicy: Delete # (Retain|Delete)
replicaCount: 1

users:
  - name: signoz
    databases:
      - signoz_metrics
      - signoz_traces
      - signoz_logs
      - signoz_meter

altinity-clickhouse-operator:
  enabled: true
