From f2ba21ba678907fac0d3d088ad09b0d140ba7740 Mon Sep 17 00:00:00 2001
From: sinanmohd <sinan@sinanmohd.com>
Date: Sat, 17 Feb 2024 11:37:23 +0530
Subject: [PATCH] Makefile: nix port

---
 Makefile | 17 ++++++++---------
 1 file changed, 8 insertions(+), 9 deletions(-)

diff --git a/Makefile b/Makefile
index 7a774b4..1efa053 100644
--- a/Makefile
+++ b/Makefile
@@ -1,9 +1,8 @@
-include /usr/share/dpkg/pkg-info.mk
+bindir = ${OUT}/bin
+docdir = ${DOC}/share/doc/ftpsync
+mandir = ${MAN}/share/man
 
-bindir = /usr/bin
-docdir = /usr/share/doc/ftpsync
 examplesdir = ${docdir}/examples
-mandir = /usr/share/man
 man1dir = ${mandir}/man1
 man5dir = ${mandir}/man5
 
@@ -41,15 +40,15 @@ install -D bin/runmirrors.$(1) $(2)/runmirrors
 endef
 
 install:
-	$(call install_bin,install,${DESTDIR}/${bindir})
-	install -D -m644 -t ${DESTDIR}/${docdir} \
+	$(call install_bin,install,${bindir})
+	install -D -m644 -t ${docdir} \
 		README.md
-	install -D -m644 -t ${DESTDIR}/${examplesdir} \
+	install -D -m644 -t ${examplesdir} \
 		etc/ftpsync.conf.sample \
 		etc/runmirrors.conf.sample \
 		etc/runmirrors.mirror.sample
-	install -D -m644 -t ${DESTDIR}/${man1dir} ${MAN1:%=doc/%.1}
-	install -D -m644 -t ${DESTDIR}/${man5dir} ${MAN5:%=doc/%.5}
+	install -D -m644 -t ${man1dir} ${MAN1:%=doc/%.1}
+	install -D -m644 -t ${man5dir} ${MAN5:%=doc/%.5}
 
 install-tar:
 	$(call install_bin,install-tar,${DESTDIR}/bin/)
-- 
2.43.0

