rustfs:
  enabled: true
  deploymentType: "statefulset"
  replicaCount: 4

  auth:
    accessKey: "changeme"
    secretKey: "changeme"

  podManagementPolicy: "Parallel"

  dataPersistence:
    enabled: true
    size: 32Gi
    storageClass: local-path

  logsPersistence:
    enabled: false

  consoleIngress:
    enabled: false
  ingress:
    enabled: false
